dictionaries = [
    "en_us",
    "ru",
]
words = [
    "adblock",
    "adwaita",
    "akkoma",
    "anki",
    "apertium",
    "archinstall",
    "arkenfox",
    "autocrypt",
    "balena",
    "betterfox",
    "bing",
    "bitwarden",
    "btrfs",
    "catodon",
    "centre",
    "chatmail",
    "chroot",
    "cloudflare",
    "codeberg",
    "cromite",
    "debloater",
    "degoog",
    "deno",
    "duckduckgo",
    "ecosia",
    "endeavour",
    "fedilab",
    "fediverse",
    "figma",
    "firefish",
    "flathub",
    "flatpak",
    "flickr",
    "floorp",
    "forgejo",
    "foss",
    "fossify",
    "friendica",
    "gboard",
    "geocoder",
    "gifsicle",
    "gitea",
    "gmail",
    "graphene",
    "greasemonkey",
    "haruna",
    "heli",
    "homebrew",
    "huawei",
    "hulbee",
    "iceraven",
    "iceshrimp",
    "imgur",
    "imput",
    "ironfox",
    "iway",
    "iwctl",
    "izzy",
    "jetpack",
    "jitsi",
    "kagi",
    "libre",
    "librewolf",
    "lingva",
    "manjaro",
    "megalodon",
    "midori",
    "misskey",
    "mojeek",
    "moshidon",
    "moshinda",
    "mullvad",
    "multilib",
    "multiplatform",
    "nicolium",
    "nilch",
    "obtainium",
    "ookla",
    "openverse",
    "outplayer",
    "pacman",
    "pandoc",
    "peertube",
    "phanpy",
    "pinterest",
    "pipilo",
    "pixabay",
    "pixelfed",
    "pleroma",
    "preact",
    "qwant",
    "rootflags",
    "rutube",
    "searxng",
    "sharkey",
    "stacher",
    "startpage",
    "subvol",
    "swisscows",
    "tampermonkey",
    "tauri",
    "timeshift",
    "tineye",
    "tokodon",
    "tooi",
    "tusky",
    "tweetbot",
    "ungoogled",
    "unsplash",
    "urwid",
    "userscripts",
    "ventoy",
    "violentmonkey",
    "wallhaven",
    "waterfox",
    "widevine",
    "winget",
    "xiaomi",
    "yandex",
    "ytdlnis",
    "автодополнение",
    "автообновлений",
    "анимациям",
    "анимированных",
    "анонимизирует",
    "анти",
    "архитектур",
    "аудиопоток",
    "аудиофайлов",
    "аудитов",
    "багами",
    "безрамочный",
    "браузерного",
    "браузерное",
    "браузерные",
    "браузерный",
    "браузерных",
    "бэкдор",
    "бэкенд",
    "видеосообщения",
    "виджетов",
    "виджеты",
    "википедии",
    "википедия",
    "вовлечённости",
    "вовлечённость",
    "геолокации",
    "геолокация",
    "двухфакторная",
    "двухфакторной",
    "дзен",
    "единоразовый",
    "капчи",
    "капчу",
    "коллаборативная",
    "коллаборативной",
    "краудсорсинг",
    "креативные",
    "криминализация",
    "криптовалютами",
    "криптовалюты",
    "кэш",
    "кэша",
    "лаунчер",
    "логгер",
    "локали",
    "локаль",
    "медиа",
    "медиапроигрывателе",
    "медиапроигрывателей",
    "мерч",
    "мессенджер",
    "мессенджера",
    "мессенджерах",
    "мессенджеров",
    "мессенджеры",
    "метапоисковая",
    "микроблогов",
    "микрокод",
    "минималистичное",
    "минималистичных",
    "многоколонный",
    "модерации",
    "моно",
    "мультиаккаунт",
    "неактивности",
    "недоверенных",
    "незашифрованные",
    "незашифрованный",
    "незашифрованных",
    "неочевидно",
    "неподдерживаемые",
    "одноразово",
    "окирпичить",
    "опциональны",
    "опциональные",
    "отрисовки",
    "отсканировать",
    "отсканируйте",
    "офлайн",
    "патчей",
    "патчи",
    "перенаправление",
    "перенаправления",
    "перенаправлениям",
    "переразметки",
    "переупорядочивать",
    "персонализируемый",
    "побитово",
    "подкасты",
    "подсанкционных",
    "портирован",
    "портированию",
    "постквантовая",
    "постобработка",
    "постобработки",
    "предпросмотр",
    "предпросмотром",
    "предустанавливают",
    "премиум",
    "пресетов",
    "пресеты",
    "приоритизирует",
    "прокси",
    "проксирование",
    "проксирует",
    "проксируются",
    "проприетарная",
    "проприетарное",
    "проприетарной",
    "проприетарные",
    "проприетарный",
    "проприетарным",
    "проприетарными",
    "проприетарных",
    "просмотрщик",
    "разблокировка",
    "разблокировки",
    "релее",
    "релеев",
    "релеем",
    "релеи",
    "релей",
    "релею",
    "релея",
    "релеями",
    "релеях",
    "репозиториев",
    "репозитории",
    "репозиторий",
    "репозиторию",
    "репозитория",
    "репозиториям",
    "репозиториями",
    "репозиториях",
    "репосты",
    "самохостинг",
    "сгенерирована",
    "сгенерированные",
    "сгенерированный",
    "сгенерированных",
    "сервисами",
    "сервисов",
    "сервисы",
    "скачивается",
    "скрапинга",
    "спамеры",
    "спидранов",
    "спонсированные",
    "стикеров",
    "стикеры",
    "стриминговые",
    "стриминговых",
    "телеграм",
    "техногигантов",
    "токены",
    "трее",
    "трекеров",
    "трекеры",
    "уязвимостей",
    "уязвимостям",
    "фреймворк",
    "фреймворки",
    "фронтенд",
    "хешем",
    "хештеги",
    "хешу",
    "чатам",
    "чатах",
    "чатов",
    "чаты",
    "шутер",
    "экологичная",
    "эксплойтов",
    "эмодзи",
    "яндекс",
    "яндексе",
    "яндексу",
]
flag_words = ["оффлайн"]
include_paths = [
    "content/**/*.md",
    "content/**/*.html",
    "data/**/*.yaml",
]
ignore_paths = [
    "**/_TEMPLATE.yaml",
    "data/contributors/*.yaml",
    "content/guides/how-to-use-console/**",
    "content/wiki/youtube/**",
    "content/wiki/winget/**",
    "content/wiki/veracrypt/**",
    "content/wiki/unhook/**",
    "content/wiki/todo-txt/**",
    "content/wiki/syncthing.md",
    "content/wiki/sponsorblock/**",
    "content/wiki/scrcpy.md",
    "content/wiki/rss.md",
    "content/wiki/localsend.md",
    "content/wiki/local-ai/**",
    "content/wiki/languagetool/**",
    "content/wiki/keepassxc/**",
    "content/wiki/email/**",
]
ignore_patterns = [
    "`[^`]*`",
    "«.*»",
    "<code>.*</code>",
    "[A-ZА-ЯЁ]+",
    "[A-Z]{2,}[a-z]+",
    '[a-z0-9-]+\.[a-z0-9]+',
    '![a-z]+ [^\s]+',
    '\{\{< card [a-z-]+ >\}\}',
]
min_word_length = 4

[[overrides]]
paths = ["content/tables/*.html"]
extra_words = ["lastmod"]
extra_ignore_patterns = ['contributors: \[.+\]']

[[overrides]]
paths = ["data/cards/*.yaml"]
extra_words = ["kttpage"]
extra_ignore_patterns = ['(obtainium|fdroidrepos)?://[^\s]+']

[[overrides]]
paths = ["data/links/*/*.yaml"]
extra_ignore_patterns = ['^    by: [^\s]+']

[[overrides]]
paths = ["data/links/software/*.yaml"]
extra_ignore_patterns = [
    '^  - type: [^\s]+',
    '^    data: (([a-z0-9-]+:)?[a-z0-9-\.]+\.)?[a-z0-9-]+$',
]
